# Generated by Django 4.2.10 on 2024-02-24 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_predapi_bankstate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predapi',
            name='FranchiseBinary',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='predapi',
            name='Industry',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
